name: Run Python Script for Mentor-Mentee Pairing

on:
  push:
    branches:
      - main  # You can change the branch as needed
  workflow_dispatch:  # Allows for manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Choose the Python version you want

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      # Run the Python script
      - name: Run mentor-mentee pairing script
        run: |
          python pair_mentors_mentees.py  # Ensure the script name matches the file name in your repo

      # Upload results as an artifact
      - name: Upload results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mentor-mentee-pairs
          path: mentor_mentee_pairs.xlsx  # The file output by your script
